# Generated by Django 3.0.2 on 2020-01-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('man', 'Erkek'), ('women', 'Kadin'), ('unisex', 'UniSex')], default='unisex', max_length=6),
        ),
    ]
