# Generated by Django 3.0.2 on 2020-01-24 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='createt_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='page',
            name='slug',
        ),
        migrations.AlterField(
            model_name='page',
            name='cover_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.TextField(choices=[('draft', 'taslak'), ('published', 'yayinlandi'), ('deleted', 'silindi')]),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=75),
        ),
    ]
