# Generated by Django 3.0.2 on 2020-01-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20200124_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='cover_image',
            field=models.ImageField(upload_to='page'),
        ),
    ]
